# Generated by Django 5.0.1 on 2024-02-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
